package guru.springframework.domain;

// Created in lecture 103
// Lecture 119 Exclude Recipe from hashCode generated by Lombok

import lombok.*;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

@Data
@Entity
@EqualsAndHashCode(exclude = {"recipes"})
public class Category {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String description;

    // This is mapped by the categories attribute in the Recipe class. Use a set to
    //    enforce uniqueness
    // Lecture 108 Must initialize set before adding to it or get exception
    @ManyToMany(mappedBy = "categories")
    private Set<Recipe> recipes = new HashSet<>();

}
